### ISSUE TITLE
Filter menu on members list should stay open

### ISSUE THREAD

**Issue by wsv-accidis** [wsv-accidis/tmeit-android#2]
The menu of filter options on the members list closes once the user makes a selection. Instead, it should stay open so the user can apply/remove multiple filters easily.

**Comment by loffa** [comment]
The app should also have either group or team as selected and not both.

**Comment by wsv-accidis** [comment]
Nah, I want the group/team filters to be separate. Otherwise there's no way to combine them. If many users request them to be exclusive I'll change my mind.

**Comment by wsv-accidis** [comment]
Turns out this is not possible to do with the default Android options menu. Bigger refactoring required to use a completely custom menu.
