### ISSUE TITLE
Number of workers on the event list doesn't update

### ISSUE THREAD

**Issue by RickardZwahlen** [wsv-accidis/tmeit-android#20]
The worker count (3/20 etc) in the "our events"-list doesn't update as often as the worker count inside the event. It is possible to see 0/20 for an event in the list, then click on it and see 1/20, and then go back to the list and still see 0/20.

**Comment by wsv-accidis** [comment]
This is a known issue with how the data layer in the app works. The lists are very aggressively cached to speed up load times, meaning that there may be stale data. This applies everywhere, not just events.

The fix is to trigger a refresh of a list when an entity contained within has been updated.
