### ISSUE TITLE
Marskalk without assigned team shown in incorrect cases.

### ISSUE THREAD

**Issue by trubb** [wsv-accidis/tmeit-android#25]
Members who are not assigned to a team will be listed as long as their assigned group is displayed.

For example:
Selecting the team Vraq, and the group Marskalk will show unassigned Marskalks, even though they are not part of the team, nor the group, Vraq.
Same goes for selecting an active team and the group marskalk. By doing so all the correct team members that are Marskalks will show, but also the people who are not assigned to a team.

As all Prao, Mästare, and Vraq are currently assigned to a team I have been unable to confirm wether or not this issue also applies to these groups.

**Comment by wsv-accidis** [comment]
Reproduced.
