### ISSUE TITLE
People counter for the doors in the chapter room

### ISSUE THREAD

**Issue by loffa** [wsv-accidis/tmeit-android#28]
Implement a counter that can be used in the doors by our staff.

Two counters is needed, one for members and one for external guests. Should also give some kind of warning if the count reaches 150 people or if it is close to 50/50 in members vs. external guests.

Preferably this counter should be synced between all devices which have it open.

**Comment by trubb** [comment]
While a great feature it might be more beneficial to break off into it's own project, preferably bundled into some sort of Kistan-app as it is useful for all parts of the chapter. Preferably together with features for controlling music, lights, and more. Very likely a good project for the programming events ITK proposed should take place together with other committees..

**Comment by wsv-accidis** [comment]
Agree that this is potentially a different app, or possibly a component that could be integrated into different apps.

However, this is a much more complex problem than it first seems because there needs to be an authenticated backend of some sort managing the count, it needs to handle distributed updates (multiple updates) in a safe way and there probably needs to be access control, unless we want anyone with any associated app to be able to change the counter from anywhere in the world.

**Comment by loffa** [comment]
I want to have this as a feature while working pubs. A simple counter on one device is better than no counter at all. the possibility to control Music, Light and more are features that can be built for a bigger app. But doing that is a lot of work compared to a some simple buttons in a layout. I also don't think that all users should be able to control Kistan's sound and light from anywhere.

If we decide to do this over network int feature we could probably implement it as an API that Qmisk and TMEIT can have in their apps or as a separate website.

**Comment by loffa** [comment]
My plan is to implements this feature as a "single phone" system.

**Comment by wsv-accidis** [comment]
If all you need is a single counter on a single phone, surely there are apps that do this already? I've seen people at the door use their phones to keep count.

**Comment by trubb** [comment]
While not equipped with quite as many features as proposed, there are indeed many apps for counting with features comparable to, or greater than, those of the "Clickers" that we use for counting votes on Chapter Meetings.
I still believe this feature is disparate enough to be separated from the TMEIT-app, no matter how many devices the count will be synced over.

**Comment by wsv-accidis** [comment]
I agree with @trubb, there's no need for this feature in the app unless it does something that's unique to TMEIT and sets it apart from the generic apps that are already out there.

As he is the webmarskalk-elect I would love to have @RickardZwahlen's input on this as well.

**Comment by RickardZwahlen** [comment]
There are counter apps that do this perfectly well, and take a minute to install if needed. A synched solution is more work than the tool is worth. That being said, a local counter feature would not take a lot of extra space, so I'm not adversed to it if some workers would find it helpful. I will simply not put any effort into implementing it.

**Comment by wsv-accidis** [comment]
Based on contributor input I'm closing this issue.
