### ISSUE TITLE
Show additional/larger profile images on member info page

### ISSUE THREAD

**Issue by loffa** [wsv-accidis/tmeit-android#3]
A possibility to see the image in full scalen if you click on it. The ability to swipe thrue all pictures on that page.

**Comment by wsv-accidis** [comment]
There aren't really any full scale images. The originals on the backend are 120x110 pixels which means they are actually upscaled on modern phones even in the current view. Showing them even larger would be a blurry mess.

However, being able to show all the images somehow (swiping, or perhaps a gallery page) is a nice feature which I would love to have.
